version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "3000:3000"

  db:
    build: ./db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro